const TEAM_DATA_IS_LOADING = 'TEAM_DATA_IS_LOADING';
const TEAM_DATA_HAS_ERROR = 'TEAM_DATA_HAS_ERROR';
const TEAM_FETCH_DATA_SUCCESS = 'TEAM_FETCH_DATA_SUCCESS';
const TEAM_FILTER = 'TEAM_FILTER';
const PROJECTS_DATA_IS_LOADING = 'PROJECTS_DATA_IS_LOADING';
const PROJECTS_DATA_HAS_ERROR = 'PROJECTS_DATA_HAS_ERROR';
const PROJECTS_FETCH_DATA_SUCCESS = 'PROJECTS_FETCH_DATA_SUCCESS';
const PROJECTS_FILTER = 'PROJECTS_FILTER';
const SET_TASKS_FILTER = 'SET_TASKS_FILTER';
//const SHOW_ALL_TASKS = 'SHOW_ALL_TASKS';
//const SHOW_SORT_INC_TASKS = 'SHOW_SORT_INC_TASKS';
//const SHOW_SORT_DEC_TASKS = 'SHOW_SORT_DEC_TASKS';
//const SHOW_SORT_TASKS_BY_PERSON = 'SHOW_SORT_TASKS_BY_PERSON';
const CALENDAR_DATA_IS_LOADING = 'CALENDAR_DATA_IS_LOADING';
const CALENDAR_DATA_HAS_ERROR = 'CALENDAR_DATA_HAS_ERROR';
const CALENDAR_FETCH_DATA_SUCCESS = 'CALENDAR_FETCH_DATA_SUCCESS';

export {
    TEAM_DATA_IS_LOADING,
    TEAM_DATA_HAS_ERROR,
    TEAM_FETCH_DATA_SUCCESS,
    TEAM_FILTER,
    PROJECTS_DATA_IS_LOADING,
    PROJECTS_DATA_HAS_ERROR,
    PROJECTS_FETCH_DATA_SUCCESS,
    PROJECTS_FILTER,
    SET_TASKS_FILTER,
    //SHOW_ALL_TASKS,
    //SHOW_SORT_INC_TASKS,
    //SHOW_SORT_DEC_TASKS,
    //SHOW_SORT_TASKS_BY_PERSON,
    CALENDAR_DATA_IS_LOADING,
    CALENDAR_DATA_HAS_ERROR,
    CALENDAR_FETCH_DATA_SUCCESS,
}